FROM amazonlinux:latest

# Install AWS CLI
RUN echo "Installing AWS CLI..."
RUN yum -y install which unzip aws-cli

# Install Terraform
RUN echo "Installing Terraform..."
RUN curl -O https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
RUN unzip terraform_0.12.26_linux_amd64.zip -d /usr/bin/

# Copy over the test Terraform and setup script
WORKDIR /temp
COPY setup.sh /temp
RUN chmod +x setup.sh

# make terraform dir to hold scripts
RUN mkdir terraform

# transfer terraform files to perspective dir
WORKDIR /temp/terraform

# make dir(s)
RUN mkdir webApp
RUN mkdir windowsApp
RUN mkdir msmq

# webApp
WORKDIR /temp/terraform/webApp
RUN curl -O https://github.com/Gamemastertwig/CloudCarryout/blob/master/Terraform/webApp/EC2Linux.tf
RUN curl -O https://github.com/Gamemastertwig/CloudCarryout/blob/master/Terraform/webApp/loadBalancer.tf
RUN curl -O https://github.com/Gamemastertwig/CloudCarryout/blob/master/Terraform/webApp/sqlLin.tf

# windowsApp
WORKDIR /temp/terraform/windowsApp
RUN curl -O https://github.com/Gamemastertwig/CloudCarryout/blob/master/Terraform/windowsApp/ec2Win.tf
RUN curl -O https://github.com/Gamemastertwig/CloudCarryout/blob/master/Terraform/windowsApp/sqlWin.tf

# msmq
WORKDIR /temp/terraform/msmq
RUN curl -O https://github.com/Gamemastertwig/CloudCarryout/blob/master/Terraform/msmq-s3/que.tf
RUN curl -O https://github.com/Gamemastertwig/CloudCarryout/blob/master/Terraform/msmq-s3/s3.tf

# return to temp workdir
WORKDIR /temp

ENTRYPOINT [ "./setup.sh" ]